### ISSUE TITLE
문서화 작업

### ISSUE THREAD

**Issue by sukso96100** [ubuntu-kr/hanjp-im#40]
추후 신규 참여자 유입때와 기존 참여자 이탈로 구성원이 완전히 달라져도, 프로젝트 유지가 가능하도록 프로젝트에 관한 문서화가 필요함.

- 개발환경 구축 방법
- 의존성 설치 및 컴파일(빌드) 방법
- 실행파일 실행하여 기능 테스트 하는 방법
- 코딩 스타일, 커밋 메시지 스타일, 코드 수정 가이드
- 프로젝트 구조와 프로그램 작동 과정에 대한 설명
- 프로젝트에서 사용하는 기술과 라이브러리
- 브랜치 관리 방법과 절차

- 이슈 제출 가이드라인
- 이슈 관리 가이드라인
- PR 제출 가이드라인
- PR 검토, 승인 가이드라인

- 프로젝트 마일스톤과 로드맵에 관한 정보가 담긴 문서
- 지금까지 구현된 기능과 앞으로 구현이 필요한 기능

문서화 더 필요한 항목이 있다면 커멘트 바랍니다.

**Comment by onting** [comment]
Please reopen with English as it needed.

**Comment by reyoucat** [comment]
윗분도 궁금한가봅니다. English Wiki 가 필요 할 것 같군요.

* readme.md 파일에서 wiki 링크
* 분야를 잘 몰라서, mac 서포트가 가능할까요?
* 한자 변환까지 되지 않았다면 저도 한번 살짝 참가해보고 싶습니다.

**Comment by onting** [comment]
네 참여는 언제든 환영입니다. mac 서포트는 바라던 부분중 하나입니다.
다만 문서적인 면에서 정비되지 않은 점들이 많아서 이번주 화요일까지 정리한뒤에 메일로 회신드리겠습니다.
지금 한자 변환은 지원되지 않고 libkkc로 libhanjp에 feature 추가할 예정입니다.
그리고 이제 영어를 기준으로 소통할거라서 한국어 이슈는 영어가 능숙하지 않은 분들과만 소통하는 용도로 이용할 예정입니다.

**Comment by sukso96100** [comment]
@reyoucat 저희 프로젝트가 컨트리뷰션 아카데미에 참여하니 관심 있으시면 이 프로그램 통해서 기여 해 보시는 것도 좋을 것 같네요 :) https://contributionacademy.oopy.io/
