### ISSUE TITLE
CI/CD 적용

### ISSUE THREAD

**Issue by sukso96100** [ubuntu-kr/hanjp-im#41]
추후 컨트리뷰터의 급격한 증가로 인해 PR 리뷰으할 숫자도 급격히 늘어날 때와  메인테이너가 개인 사정 등으로 리뷰가 어려워도 PR 이 자동으로 검토되도록 검토를 자동화 할 필요가 있음.

- GitHub Actions 활용하여 구현 권장
- 문법 검사
- 정상 빌드 가능 여부 검사
- 각 로직 정상 작동 여부 검사
  - 특히 한글 - 가나, 가나 - 한자 변환 로직과 오토마타 등 핵심적인 부분 정상 작동 여부 확인 자동화 필요.

추가로 더 필요한 커멘트 바랍니다.

**Comment by onting** [comment]
Please reopen with English as it needed.
